package com.serviceabonnement.enums;

public enum TypeNotification {
    CONFIRMATION_SOUSCRIPTION, ECHEC_SOUSCRIPTION,
    RAPPEL_EXPIRATION,
    RENOUVELLEMENT_EFFECTUE, RENOUVELLEMENT_ECHOUE,
    ANNULATION_EFFECTUEE, ANNULATION_ECHOUEE,
    ANNULATION_ADMIN_EFFECTUE, ANNULATION_ADMIN_EFFECTUEE,
    SUSPENSION_EFFECTUEE, SUSPENSION_ECHOUEE,
    MODIFICATION_EFFECTUE, MODIFICATION_ECHOUEE,
    REUSSITE_REMBOURSEMENT, ECHEC_REMBOURSEMENT,
    DESACTIVATION_EFFECTUEE, DESACTIVATION_ECHOUEE
}
