global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # ---------------------------------------------------------------
  #  G1 — (ajoutez votre bloc ici)
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  #  G2 — Service Abonnement (SGITU)
  # ---------------------------------------------------------------
  - job_name: 'service-abonnement'
    static_configs:
      - targets: ['service-abonnement:8082']
    metrics_path: '/actuator/prometheus'

  # ---------------------------------------------------------------
  #  G3 — (ajoutez votre bloc ici)
  # ---------------------------------------------------------------


  # ---------------------------------------------------------------
  #  G4 — (ajoutez votre bloc ici)
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  #  G5 — (ajoutez votre bloc ici)
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  #  G6 — (ajoutez votre bloc ici)
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  #  G7 — (ajoutez votre bloc ici)
  # ---------------------------------------------------------------
  

  # ---------------------------------------------------------------
  #  G8 — (ajoutez votre bloc ici)
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  #  G9 — (ajoutez votre bloc ici)
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  #  G10 — (ajoutez votre bloc ici)
  # ---------------------------------------------------------------
