apiVersion: v1
kind: Service
metadata:
  name: g7-suivi-vehicule
  namespace: sgitu-g7
  labels:
    app: g7-suivi-vehicule
spec:
  type: ClusterIP
  selector:
    app: g7-suivi-vehicule
  ports:
    - name: http
      port: 8087
      targetPort: 8087
