apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sgitu-g7
resources:
  - namespace.yaml
  - 01-configmap.yaml
  - 02-secret.yaml
  - 03-postgres.yaml
  - 04-kafka.yaml
  - 05-deployment.yaml
  - 06-service.yaml
commonLabels:
  app.kubernetes.io/name: g7-suivi-vehicule
  app.kubernetes.io/part-of: sgitu
  group: G7
