# APPLICATION
spring.application.name=g7-suivi-vehicules
server.port=8087

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/g7_vehicules
spring.datasource.username=g7user
spring.datasource.password=g7password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# KAFKA
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=g7-group
spring.kafka.consumer.auto-offset-reset=earliest

kafka.topic.anomalie=g7.anomalie.detectee
kafka.topic.position=g7.position.updated
kafka.topic.incident=g7.incident.signale
kafka.topic.telemetrie=g7.telemetrie.stream

# JWT
jwt.secret=sgitu_g7_secret_key_2025_very_long_secret
jwt.expiration=86400000

# SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always