# APPLICATION
spring.application.name=g7-suivi-vehicules
server.port=8087

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/g7_vehicules
spring.datasource.username=g7user
spring.datasource.password=g7password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# KAFKA
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=g7-group
spring.kafka.consumer.auto-offset-reset=earliest
# Fail fast si Kafka est absent (evite le blocage de 60s)
spring.kafka.producer.properties.max.block.ms=500
spring.kafka.producer.properties.delivery.timeout.ms=1000
spring.kafka.producer.properties.request.timeout.ms=500

kafka.topic.anomalie=anomalies-terrain
kafka.topic.position=vehicule-positions
kafka.topic.incident=suivi-vehicule.incident.topic
kafka.topic.telemetrie=g7.telemetrie.stream
kafka.topic.g8=g8.vehicule.status
kafka.topic.vehicle.registered=vehicle.registered
# JWT
jwt.secret=sgitu_g7_secret_key_2025_very_long_secret
jwt.expiration=86400000

# SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# SEUILS ANOMALIES
anomalie.seuil.vitesse.max=80.0
anomalie.seuil.temperature.critique=100.0
anomalie.seuil.carburant.critique=5.0
anomalie.seuil.immobilisation.minutes=5
anomalie.seuil.freinage.deceleration=-4.0
anomalie.immobilisation.rayon.metres=50.0
anomalie.immobilisation.nb.positions=10

# G9 INTEGRATION
g9.integration.url=http://localhost:8089/api/v1/incidents

# G5 INTEGRATION
g5.notification.url=http://notification-service:8085/api/notifications/send

# CACHE (Caffeine)
# TTL 5 minutes : les seuils sont rechargés depuis la DB toutes les 5 min max
# La modification via API invalide le cache immédiatement (@CacheEvict)
# autres
spring.cache.type=caffeine
spring.cache.cache-names=seuils
spring.cache.caffeine.spec=maximumSize=50,expireAfterWrite=5m