package com.serviceabonnement.dto.enums;

public enum NotificationEventType {
    CONFIRMATION_SOUSCRIPTION,
    ECHEC_SOUSCRIPTION,
    RAPPEL_EXPIRATION,
    RENOUVELLEMENT_EFFECTUE,
    RENOUVELLEMENT_ECHOUE,
    ANNULATION_EFFECTUEE,
    ANNULATION_ECHOUE,
    SUSPENSION_EFFECTUEE,
    SUSPENSION_ECHOUE,
    DESACTIVATION_EFFECTUEE,
    DESACTIVATION_ECHOUEE,
    MODIFICATION_EFFECTUEE,
    MODIFICATION_ECHOUE
}
