spring.application.name=service-billetterie
server.port=8081

#Database
spring.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Payment Service
payment.service.url=http://localhost:8086
# Coordination microservice
coordination-service.url=http://localhost:8084
