package com.ensate.billetterie.ticket.mapper;

import com.ensate.billetterie.ticket.domain.entity.Ticket;
import com.ensate.billetterie.ticket.domain.entity.TransferRecord;
import com.ensate.billetterie.ticket.dto.request.CreateTicketRequest;
import com.ensate.billetterie.ticket.dto.response.TicketResponse;
import com.ensate.billetterie.ticket.dto.response.TransferRecordResponse;
import org.mapstruct.*;

import java.util.List;

@Mapper(
        componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS
)
public interface TicketMapper {

    // ─── Entity → Response ───────────────────────────────────────────────

    @Mapping(target = "transferHistory", source = "transferHistory")
    TicketResponse toResponse(Ticket ticket);

    List<TicketResponse> toResponseList(List<Ticket> tickets);

    //TransferRecordResponse toTransferRecordResponse(TransferRecord transferRecord);

    // ─── CreateRequest → Entity ───────────────────────────────────────────

    @Mapping(target = "id",              ignore = true)
    @Mapping(target = "tokenValue",      ignore = true)   // generated by IdentityService
    @Mapping(target = "status",          ignore = true)   // defaults to ISSUED via @Builder.Default
    @Mapping(target = "transferHistory", ignore = true)   // starts empty
    @Mapping(target = "issuedAt",        ignore = true)   // @CreatedDate
    @Mapping(target = "updatedAt",       ignore = true)   // @LastModifiedDate
    @Mapping(target = "flaggedAt",       ignore = true)
    @Mapping(target = "redeemedAt",      ignore = true)
    @Mapping(target = "refundedAt",      ignore = true)
    @Mapping(target = "cancelledAt",     ignore = true)
    @Mapping(target = "deletedAt",       ignore = true)
    @Mapping(target = "transferredAt",   ignore = true)
    Ticket toEntity(CreateTicketRequest request);

    // ─── Patch / update helper ────────────────────────────────────────────

    /**
     * Copies non-null fields from {@code request} onto an existing {@code ticket}.
     * Useful if you ever add a PATCH endpoint.
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "id",              ignore = true)
    @Mapping(target = "tokenValue",      ignore = true)
    @Mapping(target = "status",          ignore = true)
    @Mapping(target = "transferHistory", ignore = true)
    @Mapping(target = "issuedAt",        ignore = true)
    @Mapping(target = "updatedAt",       ignore = true)
    @Mapping(target = "flaggedAt",       ignore = true)
    @Mapping(target = "redeemedAt",      ignore = true)
    @Mapping(target = "refundedAt",      ignore = true)
    @Mapping(target = "cancelledAt",     ignore = true)
    @Mapping(target = "deletedAt",       ignore = true)
    @Mapping(target = "transferredAt",   ignore = true)
    void updateEntityFromRequest(CreateTicketRequest request, @MappingTarget Ticket ticket);
}
